### PR TITLE
[fdsnxml] Fix numbering of poles and zeros

### PR DESCRIPTION
**Pull request by andres-h**
It seems the numbering of both poles and zeros should start from 0:

http://docs.fdsn.org/projects/stationxml/en/latest/reference.html#pole

### CODE REVIEW

**Comment by gempa-jabe** [comment]
> The position index of the pole (or zero)

I read it in a way that zero is meant  for unset otherwise it is the index.

**Review by gempa-jabe — APPROVED** [review]
The code is fine but semantics is still not clear to me. Sometimes fdsnws XML starts counting at 1 and sometimes at 0. Can you give a reference to how exactly this index must be interpreted?

**Comment by andres-h** [comment]
I don't have more info than provided by the first link. I don't think it makes sense to have unset poles or zeros, but maybe for safety the index should start from 1...

**Comment by gempa-jabe** [comment]
As the fdsnws at IRIS also starts counting from 0, let's merge that.

**Pull request merged**
