### PR TITLE
[scdispatch] add option create-notifier

### PR DESCRIPTION
**Pull request by luca-s**
This add an option to work without messaging system and using `scdispatch`+`scdb` instead. 

```
scdispatch -i test.xml -O operation --create-notifier notifier.xml
scdb -i notifier.xml
```

### CODE REVIEW

**Comment by gempa-jabe** [comment]
In other tools, `--create-notifier` just switches the mode of operation but does not receive an output file. I recommend to output the archive to stdout and let the user redirect it to a file of her choice or add `-o` to define an output file. Or both: default stdout, `-o` in addition. Similar to `scinv` and `bindings2cfg`.

**Comment by luca-s** [comment]
I  initially sent everything to standard output, but the tool writes to standard output too. Is it ok if I convert every usage of std::cout and std::cerr to SEISCOMP_INFO/SEISCOMP_WARNING ?

**Comment by gempa-jabe** [comment]
Yes, sure. This was one of our first tools and using the proper macros is OK. You can remove all stdout output which should not be captured by a user or replace it with stderr if necessary.

**Comment by gempa-jabe** [comment]
Done?

**Comment by luca-s** [comment]
Yes. I noticed some indentations were not correct I wanted them right

**Comment by gempa-jabe** [comment]
It is looking good to me.

**Pull request merged**
