### PR TITLE
[fdsnws] Change ExportSink API

### PR DESCRIPTION
**Pull request by andres-h**
Change ExportSink.write(unicode, length) to ExportSink.write(bytes) to fix unicode XML.

### CODE REVIEW

**Comment by gempa-stephan** [comment]
Also I suggest to increment the patch version of the event and station service as they are affected by this change.

What about the access log. It will from now on contain the number of bytes instead of characters for XML requests where as text requests are still counted in characters. Should we convert the bytes back to unicode and count them in chars as before or rather convert the chars in the text request to bytes as bytes are probably the unit one would expect in the log.

Also the debug output in https://github.com/SeisComP/main/blob/0fd7a916758e12a34f164e2b37f6abf9e5b7dcb5/apps/fdsnws/fdsnws/event.py#L569 and https://github.com/SeisComP/main/blob/0fd7a916758e12a34f164e2b37f6abf9e5b7dcb5/apps/fdsnws/fdsnws/station.py#L469 should be change to bytes.

**Comment by andres-h** [comment]
> @andres-h Could you please add a test case with the unicode document which was not working with the old ExportSink

This would be not be easy. AFAICS, the Exporter output must have a unicode character, such that one half of the character fits in the first 512 byte chunk and the next half in the next 512 byte chunk. This depends on the Exporter implementation and other conditions (eg., length of timestamps in bytes). Shift of output by one byte would not trigger the bug anymore, because the whole character would be in one chunk.

Personally I think the existing unicode test cases are enough.

**Comment by andres-h** [comment]
> What about the access log. It will from now on contain the number of bytes instead of characters for XML requests where as text requests are still counted in characters. Should we convert the bytes back to unicode and count them in chars as before or rather convert the chars in the text request to bytes as bytes are probably the unit one would expect in the log.

I would count bytes, which is/was the case with Python 2 anyway.

**Comment by FMassin** [comment]
Dear @andres-h, dear @gempa-stephan,

I think one of our tool, sceewlog ([doc](file:///Users/fred/Documents/Projects/NaiNo-Kami/SeisComP/SED-EEW-SeisComP-contributions-1/doc/build-doc/html/apps/sceewlog.html), [source](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/blob/aa56c57422a4aa2eed173546cc12a04b682d244b/apps/eew/sceewlog/ud_interface.py#L35)) is dependent on this and now crashes while ran within a fresh install:
```bash
14:30:09 [debug] Received pick smi:ch.ethz.sed/sc20d/Pick/NLoT_apick/20220721143009.790998.61578
14:30:09 [debug] Received origin smi:ch.ethz.sed/sc20d/Origin/20220721143009.826881.52413
14:30:09 [debug] Received event smi:ch.ethz.sed/sc20d/Event/2022ogbuqe
14:30:09 [debug] originId smi:ch.ethz.sed/sc20d/Origin/20220721143009.826881.52413 -> event smi:ch.ethz.sed/sc20d/Event/2022ogbuqe
14:30:10 [debug] Received MVS magnitude for origin smi:ch.ethz.sed/sc20d/Origin/20220721143009.826881.52413
14:30:10 [debug] Start report generation timer for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220721143010.754994.24104923 
14:30:10 [info] Number of updates 1 for event smi:ch.ethz.sed/sc20d/Event/2022ogbuqe
14:30:10 [info] lat: 46.365868; lon: 6.857574; mag: 2.399998; ot: 2022-07-21T14:30:01.5767Z
14:30:10 [debug] likelihood comment received for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220721143010.754994.24104923 
14:30:10 [debug] Processing comment likelihood for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220721143010.754994.24104923 
14:30:10 [info] likelihood value: 0.024
14:30:10 [debug] NO UPDATE SENT YET
14:30:10 [debug] Evaluation for Profile: global...
14:30:10 [debug] Sending and alert....
14:30:10 [debug] Sending an alert for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220721143010.754994.24104923 
terminate called after throwing an instance of 'Swig::DirectorMethodException'
  what():  SWIG director method error. Error detected when calling 'ExportSink.write'
Aborted (core dumped)
```

I tried to modify `ud_interface.py`:
```python 
class Sink(ExportSink):
    def __init__(self, buf):
        ExportSink.__init__(self)
        self.buf = buf
        self.written = 0
    def write(self, data): #, size):
        self.buf.write(data) #b_str(data[:size]))
        self.written += len(data) #size
        return size
```

Without success (same crash)... Any help?

Cheers

Fred

**Comment by gempa-jabe** [comment]
Make sure that write received binary data and not a unicode string.

What is actually `size` in your code that you return?

**Comment by FMassin** [comment]
Hi @gempa-jabe 

Yes sorry, I'm now trying the following:
```python
 from twisted.internet import reactor                                                                                                                                                                                                                                                
  def writeTSBin(req, data):
      reactor.callFromThread(req.write, data)
  
  class Sink(ExportSink):
      def __init__(self, request):#buf):
          ExportSink.__init__(self)
          self.request = request #self.buf = buf
          self.written = 0
  
      def write(self, data): #, size):
          if self.request._disconnected: #pylint: disable=W0212
              return -1
          writeTSBin(self.request, data) #self.buf.write(data) #b_str(data[:size]))
          self.written += len(data) #size
          return len(data) #size
```

**Comment by gempa-jabe** [comment]
You don't need `writeTSBin` as your tool is not running within Twisted. It should be enough to call `self.buf.write(data)` and return `len(data)`.

**Comment by FMassin** [comment]
> Hi @gempa-jabe
> 
> Yes sorry, I'm now trying the following:
> 
> ```python
>  from twisted.internet import reactor                                                                                                                                                                                                                                                
>   def writeTSBin(req, data):
>       reactor.callFromThread(req.write, data)
>   
>   class Sink(ExportSink):
>       def __init__(self, request):#buf):
>           ExportSink.__init__(self)
>           self.request = request #self.buf = buf
>           self.written = 0
>   
>       def write(self, data): #, size):
>           if self.request._disconnected: #pylint: disable=W0212
>               return -1
>           writeTSBin(self.request, data) #self.buf.write(data) #b_str(data[:size]))
>           self.written += len(data) #size
>           return len(data) #size
> ```
Damn:
```
09:17:21 [info] lat: 48.494122; lon: 9.546738; mag: 1.869999; ot: 2022-07-22T09:16:50.5525Z
09:17:21 [debug] likelihood comment received for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220722091721.481398.32246933 
09:17:21 [debug] Processing comment likelihood for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220722091721.481398.32246933 
09:17:21 [info] likelihood value: 0.3
09:17:21 [debug] NO UPDATE SENT YET
09:17:21 [debug] Evaluation for Profile: global...
09:17:21 [debug] Sending and alert....
09:17:21 [debug] Sending an alert for magnitude smi:ch.ethz.sed/sc20d/Magnitude/20220722091721.481398.32246933 
terminate called after throwing an instance of 'Swig::DirectorMethodException'
  what():  SWIG director method error. Error detected when calling 'ExportSink.write'
Aborted (core dumped)
```

**Comment by FMassin** [comment]
> You don't need `writeTSBin` as your tool is not running within Twisted. It should be enough to call `self.buf.write(data)` and return `len(data)`.

OK, now trying:
```python
class Sink(ExportSink):
    def __init__(self, request): #buf):
        ExportSink.__init__(self)
        self.request = request #self.buf = buf
        self.written = 0 

    def write(self, data): #, size):
        if self.request._disconnected: #pylint: disable=W0212
            return -1                                                                                                                                                                                                                                                                   
        self.request.write(data) #self.buf.write(data) #b_str(data[:size]))
        self.written += len(data) #size
        return len(data) #size

```

**Comment by gempa-jabe** [comment]
What are you doing actually? You are not dealing with requests (like a web server such as FDSNWS) but with simple buffers. There is not such attribute like `_disconnected`. This will for sure raise an exception and cause a crash. Rename `request` to `buf` to make things clear and don't mess up your code with copy and paste. Just my advice.

**Comment by FMassin** [comment]
That works! Thanks a lot @gempa-jabe !

**Pull request merged**
