### PR TITLE
[fdsnxml] add test cases of latest development

### PR DESCRIPTION
**Pull request by andres-h**

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Unfortunately the test case does not fail although the required fix for `setSensor` is not yet there. Wouldn't it make sense to capture that?

**Comment by gempa-jabe** [comment]
Sorry, it failed now. I forget to run cmake to include the test. Nevermind.

**Comment by gempa-jabe** [comment]
CentOS7 is failing:

```
1: Test command: /home/sysop/gitlocal/seiscomp/build/bin/test_fdsnxml2inv
1: Test timeout computed to be: 9.99988e+06
1: Running 2 test cases...
1: unknown location(0): fatal error in "CheckConvert2SCXML": std::runtime_error: regex_error
1: /home/sysop/gitlocal/seiscomp/src/base/main/apps/tools/inventory/fdsnxml2inv/test/test_fdsnxml2inv.cpp(93): last checkpoint
1: 
1: *** 1 failure detected in test suite "SeisComP"
1/1 Test #1: test_fdsnxml2inv .................***Failed    0.02 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
          1 - test_fdsnxml2inv (Failed)
Errors while running CTest
```

Could you check that? Anything wrong with the regular expression or does gcc 4.8.5 not support it correctly?

**Comment by andres-h** [comment]
Maybe it needs the std::regex::extended option. I will check.

**Comment by gempa-jabe** [comment]
Please install and use cmake3.

**Comment by andres-h** [comment]
It seems that regex wasn't supported before GCC 4.9. Would using boost::regex be an option?

```patch
--- a/apps/tools/inventory/fdsnxml2inv/test/test_fdsnxml2inv.cpp
+++ b/apps/tools/inventory/fdsnxml2inv/test/test_fdsnxml2inv.cpp
@@ -20,8 +20,8 @@
 #include <seiscomp/unittest/unittests.h>
 
 #include <iostream>
-#include <regex>
 
+#include <boost/regex.hpp>
 #include <boost/iostreams/stream.hpp>
 #include <boost/iostreams/device/back_inserter.hpp>
 
@@ -99,7 +99,7 @@ BOOST_AUTO_TEST_CASE(CheckConvert2SCXML) {
        string expected = oss.str();
 
        // remove dynamically generated publicIDs
-       regex rx("publicID=\"[^\"]*\"|sensor=\"[^\"]*\"|datalogger=\"[^\"]*\"");
+       boost::regex rx("publicID=\"[^\"]*\"|sensor=\"[^\"]*\"|datalogger=\"[^\"]*\"");
        BOOST_CHECK_EQUAL(regex_replace(result, rx, string("")), regex_replace(expected, rx, string(
 }
```

**Comment by gempa-jabe** [comment]
My Ubuntu comes with gcc 9.4, my arch with gcc 12.1 and we still have to deal with that prehistoric version 4.8.5 which comes with many C++11 bugs and requires special attention. :)

Boost is an option as it is the basis for the C++11 standard library and it is available on all platforms. Sure, we are also entering another version hell with that but it should be doable for the moment. Let's give it a try. Feel free to commit that change to master.

**Pull request merged**
