### PR TITLE
Scalert: Added author filter

### PR DESCRIPTION
**Pull request by Donavin97**
- fixed some typos, also added author filter.
- Scalert: Fixed some typos, also added author filter.

### CODE REVIEW

**Comment by andres-h** [comment]
@cla-bot check

**Comment by jsaul** [comment]
To me this makes sense and looks good, thanks a lot.

But do we really need both "author" and "authors"? I think the latter would be enough.

**Comment by Donavin97** [comment]
Hi there.
You make sence, we can just leave the authors tuple in there, it would accept just 1 or multiple authors if need be.
Thanks.
Donavin.

**Comment by Donavin97** [comment]
Good day Joachim.
I made the changes you requested.
Only the authors tuple should now be used.
E.G:
authors ***@***.***, ***@***.***
This shows 2 different authors being monitored by scalert.
No other author would trigger alerts.

**Comment by andres-h** [comment]
Looks OK to me. Merged, thanks.

**Pull request merged**
