### PR TITLE
[WIP] [fdsnxml] Upgrade to version 1.1

### PR DESCRIPTION
**Pull request by gempa-jabe**
This PR aims to add support for FDSN StationXML 1.1. Once accepted then FDSN StationXML 1.0 support is dropped.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
@andres-h, added Identifier.type

**Comment by andres-h** [comment]
Does not seem to work -- I have `<Identifier type="DOI">10.15778/RESIF.FR</Identifier>`, but identifier->type() returns empty string.

Moreover, "ar << identifier" results in just `{"FDSNXML::Identifier":{}}`.

identifier->value() is correct.

**Comment by gempa-jabe** [comment]
The XML attribute registration has been forgotten.

**Comment by gempa-jabe** [comment]
Fixed.

**Comment by andres-h** [comment]
Thanks!

**Pull request merged**
