### PR TITLE
[scart] minor documentaion fixes

### PR DESCRIPTION
**Pull request by luca-s**
Forgive me, I don't mean to be pedantic, but I couldn't resist to fix a couple of documentation details :)

A bunch of options were still missing the mode (import, dump, check) for which they are intended and one was wrong `--list`.

 I also made sure the `--help`  output stays in 80 columns.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
I am fine with it and would wait for @gempa-dirk to check the changes as well. Thanks for the update.

**Comment by gempa-dirk** [comment]
@luca-s , @gempa-jabe 

Updating the options  documentations is very useful for users.

The option `-l`, `--list` does not generally work in import mode. E.g. it works with recordstreams making server requests considering time windows, e.g. fdsnws. But when importing from file, -I file://[your file], the time window filter per stream is currently not considered and a combination of `-t` and `--nslc` is the better choice at the moment. One could extend scart accordingly.

@luca-s What was wrong about `--list`? I see you made the above discussed extension but I do not see a correction.

**Comment by luca-s** [comment]
Thanks for the clarification @gempa-dirk. I  probably have a different interpretation of the `--list` option, that's why I made this change. Please let me explain my view and then let's see how we want to proceed. 

In import mode the input data is read through the `RecordStream` interface and this is true for the input being a `file` or `fdsnws` or anything. 

The `RecordStream` interface supports the filtering by time and/or streams via `RecordStream::addStream` and that is used by `scart` in input mode to apply the filtering requested by either `--list` or `--nslc`+`-t` or `-n`+`-c`+`-t`.  That means, by design, the import  mode supports time and stream filtering for all type of input, `file` included.

However the original scart code decided to [not filter](https://github.com/SeisComP/main/blob/ed9e55648baa856546f83c090272aef95a68dc45/src/trunk/apps/python/scart.py#L631) the  input in case it is `file`. So it was a choice to not call `RecordStream::addStream` in the `file` case. For this reason, my interpretation is that the original developers didn't want any time/stream filtering in the input `file`. That's why I would say that `--list` option works in input mode, that is it works for all the `RecordStream` types it is intended to work and `file` is not in them.

Now, I also understand your point: since the `file` type is the common case for the import mode, then I cannot claim `--list` option is supported in import mode. But again, it was just a developer choice.

That makes me propose the option to remove the [check on the input type](https://github.com/SeisComP/main/blob/cb7cf5e1862bf4470b4c35f27483e47c02234c75/apps/python/scart.py#L1420) and let `scart` call `RecordStream::addStream` even when the input is `file`.  What do you think about it?

**Comment by gempa-dirk** [comment]
@luca-s I have no objectives. This would be useful and unify the options and use cases. Make sure, the default RecordStream (-I file://-) is maintained.

**Comment by luca-s** [comment]
Ok then I will make the change.

 However I will also drop parts of [this](https://github.com/SeisComP/main/commit/b12a6335ca69dca4d9fbf383b0481edfe53264be) and [this](https://github.com/SeisComP/main/commit/1e63f298da9c75648500afe7633600cfdc5cb39c) commits. This is because the filtering by time/streams will be performed by the RecordStream and not requested records won't be  received by `scart`.

**Comment by luca-s** [comment]
done

**Comment by gempa-jabe** [comment]
@gempa-dirk, can it be merged?

**Comment by gempa-dirk** [comment]
@jabe Looking at the code changes without detailed testing I do not see obstacles.

**Pull request merged**
