### PR TITLE
Requestlog

### PR DESCRIPTION
**Pull request by andres-h**

### CODE REVIEW

**Review by pevans-gfz — COMMENTED** [review]
Great! Though I don't see where the use or non-use of geoIP is configured. Is something needed in [`descriptions/fdsnws.rst`](src/base/main/apps/fdsnws/descriptions/fdsnws.rst) and [`fdescriptions/dsnws.xml`](src/base/main/apps/fdsnws/descriptions/fdsnws.xml)?

**Comment by andres-h** [comment]
> I don't see where the use or non-use of geoIP is configured.

Currently it is used if the GeoIP module is found, otherwise not. But some users indeed may want to install the GeoIP module for other reasons and not use it with fdsnws, so we might need an option to force disable GeoIP.

The issue was that several users had service outages when trying to enable logging due to failing to install the correct GeoIP module.

**Comment by jschaeff** [comment]
About the configurable salt, I'm wondering:
is it mandatory for the local storage of the events (ie. exporting the requests logs to a file) ?

It is not necessary in the perspective of the centralized log system in EIDA. Because what we centralize is an aggregation, the `userid` field is hashed a second time in an HLL object (using mmh3). HLL is a mathematical object that can't be used to retrieve any personal information, it's purpose is to compute the cardinality of the userids.

So, in my opinion, implementing this yearly changing salt at the EIDA level is going to make the centralization by aggregation a real nightmare, serving no security purpose at all. Because all nodes need to use exactly the same salt, when changing the salt, all simultaneously, the cardinality of the userid can't be retrieved over a period in which the salt changed.

Let me show an example: Let's say we use all the same salt at 2021-06-01 and, by some miracle, we all manage to change simultaneously to the same salt at 2022-01-01: You can evaluate the number of users before 2022-01-01 or after 2022-01-01, but no between 2021-06-06 and 2022-06-06. The numbers will be wrong.

We have to agree to a fixed salt in all EIDA nodes that is going to never change, or not to put a salt at all. If the salt is going to be configurable, then all the aggregation system will be a failure.

**Comment by kaestli** [comment]
- I guess to overcome this one will have to provide the stats over the periods of same salt, rather than from Jan 1 to Dec. 31. 
- (However the problems may be minor, compared to the bloating of user numbers by the fact that a user uses multiple IP addresses, (work vs. vpn vs. home, wireless vs. wired networking, IPv6 vs. IPv4, personal laptop vs. institutional computing centers; and each of the IPv4 accesses may be DHCP and changing on a daily base.)

**Comment by andres-h** [comment]
Frankly I'm not sure myself if salt helps at all, because those who possess the logs have the salt as well. If userid is hashed in an HLL object, we might not need a salt. And old logs would probably have to be deleted within a year to comply with GDPR anyway.

It is also true that by using IP, the number of users would be heavily over-estimated. I've observed with SeedLink that the number of unique IPs is up to 10 times higher than the number of actual users.

**Comment by pevans-gfz** [comment]
> It is not necessary in the perspective of the centralized log system in EIDA. Because what we centralize is an aggregation, the `userid` field is hashed a second time in an HLL object (using mmh3). HLL is a mathematical object that can't be used to retrieve any personal information, it's purpose is to compute the cardinality of the userids.

The goal here is to protect user information while it resides on our server. An attacker who can examine our database (say through injection) should not be able to find out who the users are.

MMH3 (MurmurHash) "is a non-cryptographic hash function" (Wikipedia) so is unsuitable for preventing identification of users from the hashes stored on our systems. If we had to live with an old weak hash from a legacy system, that might be one thing, But designing something from scratch, let's make sure we have something not so easy to reverse. SHA256 or SHA512 might be possibilities.

**Comment by andres-h** [comment]
I think using cryptographic or non-cryptographic hash makes no difference in our case.

Non-cryptographic hash means that if you have a hash and corresponding input data, it is relatively easy to find different input data that produces the same hash. So obviously non-cryptographic hash (eg., CRC) is not suitable as a digital signature.

Regardless if we use SHA512, MD5 or simple CRC32, an attacker can scan all IP4 addresses starting from 0.0.0.0 to 255.255.255.255 and find the matching userID (if the salt is known). I don't think you can "reverse" any of those hashes to reveal arbitrary input data from a hash value only.

**Pull request merged**
