### PR TITLE
[scrttv] Allow streams with undefined coordinates if region restriction is not used

### PR DESCRIPTION
**Pull request by andres-h**

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Does that also work when sorting stations by distance from origin? I haven't checked yet.

**Comment by andres-h** [comment]
I'm waiting for next origin. So far nothing happens.

**Comment by andres-h** [comment]
"Sort by distance" does work, but the logic behind is not fully clear. Possibly the algorithm assumes (0,0) when coordinates are not defined.

Since [stationLocation()](https://github.com/SeisComP/common/blob/791c338c904ae0e2e1e175762334a2c15286dd2f/libs/seiscomp/client/inventory.cpp#L522) should throw exception, it seems that TraceState is [not set](https://github.com/SeisComP/main/blob/6f63805fb4e695ffdca49c11fc9961b56686fd89/apps/gui-qt/scrttv/mainwindow.cpp#L2417).

I suppose something similar happens when --no-inventory is used.

**Comment by gempa-jabe** [comment]
Yes, it might assume 0/0. I am fine with the change.

**Pull request merged**
